apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: nginx-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.affordable5g.network/nginx_network: "true"
  podSelector:
    matchLabels:
      io.affordable5g.network/nginx_network: "true"
