apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  EDGE_SERVER_PASSWORD: {{ .Values.api.env.EDGE_SERVER_PASSWORD | b64enc }}
  EDGE_SERVER_USER: {{ .Values.api.env.EDGE_SERVER_USER | b64enc }}
  NETWORK_FUNCTION_PASSWORD: {{ .Values.api.env.NETWORK_FUNCTION_PASSWORD | b64enc }}
  NETWORK_FUNCTION_USER: {{ .Values.api.env.NETWORK_FUNCTION_USER | b64enc }}
  OSM_PASSWORD: {{ .Values.api.env.OSM_PASSWORD | b64enc }}
  OSM_USER: {{ .Values.api.env.OSM_USER | b64enc }}
  SYSTEM_PASSWORD: {{ .Values.api.env.SYSTEM_PASSWORD | b64enc }}
  SYSTEM_USER: {{ .Values.api.env.SYSTEM_USER | b64enc }}
