apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.affordable5g.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.affordable5g.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.affordable5g.network/nginx_network: "true"
        io.affordable5g.service: web
    spec:
      containers:
        - image: nginx:1.15
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - name: affordable5g-nginxconfig
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - name: affordable5g-nginxconfig
          configMap:
             name: affordable5g-nginxconfig
status: {}
